# Generated by Django 3.1.1 on 2020-10-01 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.IntegerField(default=0)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('duration', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(7200)])),
                ('remaining', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(7200)])),
            ],
        ),
    ]
