# Generated by Django 3.1.1 on 2020-09-25 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(7200)]),
        ),
        migrations.AddField(
            model_name='task',
            name='elapsed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
