# Generated by Django 3.1.1 on 2020-10-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
