# Generated by Django 3.1.1 on 2020-09-30 04:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200925_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='remaining',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(7200)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
